include = ["**/Cargo.toml", "**/*.toml"]
exclude = ["target/**", "third_party/**"]

[formatting]
align_entries          = true
align_comments         = true
array_trailing_comma   = true
array_auto_expand      = true
array_auto_collapse    = true
column_width           = 100
indent_string          = "    "
trailing_newline       = true
reorder_keys           = false
allowed_blank_lines    = 1
crlf                   = false
